name: CI

on: [push, repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: |
        git config --global user.email "andymckay+actions@github.com"
        git config --global user.name "Andy McKay via Actions"
        git branch something-else
        git checkout something-else
        echo "foo" >> README.md
        git commit -m "Automated changes" -a
        git push --set-upstream origin something-else
        
        
